// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: relayer/relayer.proto

package relayer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "skatechain.org/api/pb/common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	// Invalid - not from operator or signature is invalid
	TaskStatus_REJECTED TaskStatus = 0
	// Taken - being aggregated with other operators signature
	TaskStatus_PROCESSING TaskStatus = 1
	// Quorum threshold is reached
	TaskStatus_ACCEPTED TaskStatus = 2
	// Quorum threshold is not reached in times
	TaskStatus_EXPIRED TaskStatus = 3
	// AVS confirmation finalized on mainnet
	TaskStatus_FINALIZED TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "REJECTED",
		1: "PROCESSING",
		2: "ACCEPTED",
		3: "EXPIRED",
		4: "FINALIZED",
	}
	TaskStatus_value = map[string]int32{
		"REJECTED":   0,
		"PROCESSING": 1,
		"ACCEPTED":   2,
		"EXPIRED":    3,
		"FINALIZED":  4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relayer_relayer_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_relayer_relayer_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_relayer_relayer_proto_rawDescGZIP(), []int{0}
}

// NOTE: (future versions) support for Solana, Sui, Aptos, etc...
type ChainType int32

const (
	ChainType_EVM ChainType = 0
)

// Enum value maps for ChainType.
var (
	ChainType_name = map[int32]string{
		0: "EVM",
	}
	ChainType_value = map[string]int32{
		"EVM": 0,
	}
)

func (x ChainType) Enum() *ChainType {
	p := new(ChainType)
	*p = x
	return p
}

func (x ChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_relayer_relayer_proto_enumTypes[1].Descriptor()
}

func (ChainType) Type() protoreflect.EnumType {
	return &file_relayer_relayer_proto_enumTypes[1]
}

func (x ChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainType.Descriptor instead.
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return file_relayer_relayer_proto_rawDescGZIP(), []int{1}
}

type TaskSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task      *Task                     `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Signature *common.OperatorSignature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TaskSubmitRequest) Reset() {
	*x = TaskSubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relayer_relayer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubmitRequest) ProtoMessage() {}

func (x *TaskSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_relayer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubmitRequest.ProtoReflect.Descriptor instead.
func (*TaskSubmitRequest) Descriptor() ([]byte, []int) {
	return file_relayer_relayer_proto_rawDescGZIP(), []int{0}
}

func (x *TaskSubmitRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskSubmitRequest) GetSignature() *common.OperatorSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    uint32    `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Msg       string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Initiator string    `protobuf:"bytes,3,opt,name=initiator,proto3" json:"initiator,omitempty"`
	ChainType ChainType `protobuf:"varint,4,opt,name=chainType,proto3,enum=common.ChainType" json:"chainType,omitempty"`
	ChainId   uint32    `protobuf:"varint,5,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Hash      []byte    `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relayer_relayer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_relayer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_relayer_relayer_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Task) GetInitiator() string {
	if x != nil {
		return x.Initiator
	}
	return ""
}

func (x *Task) GetChainType() ChainType {
	if x != nil {
		return x.ChainType
	}
	return ChainType_EVM
}

func (x *Task) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Task) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type TaskSubmitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result TaskStatus `protobuf:"varint,1,opt,name=result,proto3,enum=common.TaskStatus" json:"result,omitempty"`
}

func (x *TaskSubmitReply) Reset() {
	*x = TaskSubmitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relayer_relayer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskSubmitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubmitReply) ProtoMessage() {}

func (x *TaskSubmitReply) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_relayer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubmitReply.ProtoReflect.Descriptor instead.
func (*TaskSubmitReply) Descriptor() ([]byte, []int) {
	return file_relayer_relayer_proto_rawDescGZIP(), []int{2}
}

func (x *TaskSubmitReply) GetResult() TaskStatus {
	if x != nil {
		return x.Result
	}
	return TaskStatus_REJECTED
}

var File_relayer_relayer_proto protoreflect.FileDescriptor

var file_relayer_relayer_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a,
	0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x37, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x3d, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x2a, 0x54, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x49,
	0x4e, 0x41, 0x4c, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x14, 0x0a, 0x09, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x56, 0x4d, 0x10, 0x00, 0x32,
	0x50, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a,
	0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x19, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x73, 0x6b, 0x61, 0x74, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x6f, 0x72, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relayer_relayer_proto_rawDescOnce sync.Once
	file_relayer_relayer_proto_rawDescData = file_relayer_relayer_proto_rawDesc
)

func file_relayer_relayer_proto_rawDescGZIP() []byte {
	file_relayer_relayer_proto_rawDescOnce.Do(func() {
		file_relayer_relayer_proto_rawDescData = protoimpl.X.CompressGZIP(file_relayer_relayer_proto_rawDescData)
	})
	return file_relayer_relayer_proto_rawDescData
}

var file_relayer_relayer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_relayer_relayer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_relayer_relayer_proto_goTypes = []interface{}{
	(TaskStatus)(0),                  // 0: common.TaskStatus
	(ChainType)(0),                   // 1: common.ChainType
	(*TaskSubmitRequest)(nil),        // 2: common.TaskSubmitRequest
	(*Task)(nil),                     // 3: common.Task
	(*TaskSubmitReply)(nil),          // 4: common.TaskSubmitReply
	(*common.OperatorSignature)(nil), // 5: common.OperatorSignature
}
var file_relayer_relayer_proto_depIdxs = []int32{
	3, // 0: common.TaskSubmitRequest.task:type_name -> common.Task
	5, // 1: common.TaskSubmitRequest.signature:type_name -> common.OperatorSignature
	1, // 2: common.Task.chainType:type_name -> common.ChainType
	0, // 3: common.TaskSubmitReply.result:type_name -> common.TaskStatus
	2, // 4: common.Submission.SubmitTask:input_type -> common.TaskSubmitRequest
	4, // 5: common.Submission.SubmitTask:output_type -> common.TaskSubmitReply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_relayer_relayer_proto_init() }
func file_relayer_relayer_proto_init() {
	if File_relayer_relayer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relayer_relayer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskSubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relayer_relayer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relayer_relayer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskSubmitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relayer_relayer_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relayer_relayer_proto_goTypes,
		DependencyIndexes: file_relayer_relayer_proto_depIdxs,
		EnumInfos:         file_relayer_relayer_proto_enumTypes,
		MessageInfos:      file_relayer_relayer_proto_msgTypes,
	}.Build()
	File_relayer_relayer_proto = out.File
	file_relayer_relayer_proto_rawDesc = nil
	file_relayer_relayer_proto_goTypes = nil
	file_relayer_relayer_proto_depIdxs = nil
}
